# These are supported funding model platforms

github: [PubInv] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: ["https://www.pubinv.org/donate", www.pubinv.org]
